

data.quandl.indices <- function() {
  # List of Global Stock Market Indices / ETFs (where index not available)
  indices <- c("YAHOO/INDEX_DJI", # Dow Jones Industrial (USA)
               "YAHOO/INDEX_GSPC", # S&P 500 Index (USA)
               "YAHOO/INDEX_MID", # S&P 400 Mid-cap Index (USA)
               "YAHOO/INDEX_SML", # S&P 600 Small-cap Index (USA)
               "YAHOO/NDAQ", # NASDAQ Composite (USA)
               "YAHOO/INDEX_NYA", # NYSE Composite (USA)
               "YAHOO/INDEX_RUI", # Russel 1000 Index (USA)
               "YAHOO/INDEX_RUT", # Russel 2000 Index (USA)
               "YAHOO/INDEX_RUA", # Russel 3000 Index (USA)
               "YAHOO/INDEX_XOI", # NYSE AMEX Oil Index (USA)
               "YAHOO/INDEX_XAX", # NYSE AMEX Composite Index (USA)
               "YAHOO/INDEX_MERV", # Merval Index (Argentina)
               "YAHOO/INDEX_BVSP", # Bovespa Index (Brazil)
               "YAHOO/INDEX_MXX", # Inmex Index (Mexico)
               "YAHOO/INDEX_MXY", # NYSE ARCA Mexico Index (Mexico)
               "YAHOO/INDEX_GSPTSE", # S&P TSX Index (Canada)
               "YAHOO/INDEX_IEQR_IR", # ISEQ General Total Return Index (Ireland)
               "YAHOO/INDEX_GD_AT", # Athens Composite Index (Greece)
               "YAHOO/INDEX_FCHI", # CAC40 Index (France)
               "YAHOO/INDEX_GDAXI", # DAX Index (Germany)
               "YAHOO/INDEX_OMXC20_CO", # OMX 20 Copenhagen (Denmark)
               "GOOG/JSE_STX40", # SATRIX Top 40 (South Africa)
               "GOOG/JSE_STXIND", # SATRIX Industrials (South Africa)
               "GOOG/JSE_STXFIN", # SATRIX Financials (South Africa)
               "GOOG/JSE_STXRES", # SATRIX Resources (South Africa)
               "GOOG/JSE_STXSWX", # SATRIX SWIX (South Africa)
               "YAHOO/INDEX_CCSI", # EGX 70 Price Index (Egypt)
               "YAHOO/INDEX_RTS_RS", # Russia RTS Index (Russia)
               "YAHOO/INDEX_SSMI", # Swiss Market Index (Switzerland)
               "YAHOO/INDEX_TA100", # Tel Aviv Top 100 Index (Israel)
               "YAHOO/INDEX_STOXX50E", # Eurostoxx 50 (Europe)
               "YAHOO/INDEX_IBEX", # IBEX 35 (Spain)
               "YAHOO/INDEX_AEX", # AEX Index (Netherlands)
               "YAHOO/INDEX_BFX", # BEL20 Index (Belgium)
               "YAHOO/INDEX_ATX", # ATX Index (Austria)
               "YAHOO/INDEX_OMX", # OMX30 Index (Sweden)
               "YAHOO/INDEX_N225", # Nikkei 225 (Japan)
               "YAHOO/INDEX_JPN", # Japan AMEX Index (Japan)
               "YAHOO/INDEX_SSEC", # Shanghai Composite Index (China)
               "YAHOO/SS_000300", # CSI300 Index (China)
               "YAHOO/INDEX_HSI", # Hang Send Index (Hong Kong)
               "YAHOO/INDEX_KS11", # KOSPI Composite Index (South Korea)
               "YAHOO/INDEX_BSESN", # BSE 30 Sensitivity Index (SENSEX) (India)
               "YAHOO/INDEX_NSEI", # Nifty Fifty Index (India)
               "YAHOO/INDEX_CSE", # Colombo All Share Index (Sri Lanka)
               "YAHOO/INDEX_NZ50", # New Zealand Stock Exchange (New Zealand)
               "YAHOO/INDEX_TWII", # Taiwan Weighted Index (Taiwan)
               "YAHOO/INDEX_AORD", # All Ordinaries Index (Australia)
               "YAHOO/INDEX_AXJO", # S&P/ASX 200 Index (Australia)
               "YAHOO/INDEX_JKSE", # Jakarta Composite Index (Indonesia)
               "YAHOO/INDEX_STI") # Strait Times Index (Singapore)
  return(indices)
}
