---
output: pdf_document
---

[//]: (Welcome! This is a comment that won't get compiled into the pdf / tex.)

# Experimental Review of Market Efficiency Tests \label{chap:first}

This chapter discusses the concepts of computability and how this relates to compression.

## Experiment Design

TODO

### Signal Generators

TODO

### Randomness Generators

TODO

### Evaluation Procedure

TODO

## Market Efficiency Tests Considered

TODO

### Von Neumann Ratio

TODO

### Ljung-Box Test

TODO

### Breusch-Godfrey Test

TODO

### Augmented Dicket Fuller (ADF) Test

TODO

### The ADF-GLS Test

TODO

### Phillips-Perron Test

TODO

### Kwiatkowski–Phillips–Schmidt–Shin (KPSS) Test

TODO

### Zivot-Andrews Test

TODO

### Number of Runs Test

TODO

### Longest Run Test

TODO

### Standard Variance Ratio Test

TODO

### Multiple Variance Ratio Test

TODO

### Ranks-based Variance Ratio Test

TODO

### Signs-based Variance Ratio Test

TODO

### Multiple ranks-based Variance Ratio Test

TODO

### Multiple Signs-based Variance Ratio Test

TODO

### Universal Lossless Compression Test

TODO

## Statistical Test Results

TODO

### Results for 5-year Return Series

TODO

#### Rankings

TODO

#### Correlations

TODO

### Results for 10-year Return Series

TODO

#### Rankings

TODO

#### Correlations

TODO

### Results for 20-year Return Series

TODO

#### Rankings

TODO

#### Correlations

TODO
