# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cBitsOne <- function(x) {
    .Call('emh_cBitsOne', PACKAGE = 'emh', x)
}

cBitsZero <- function(x) {
    .Call('emh_cBitsZero', PACKAGE = 'emh', x)
}

cRunsNumber <- function(x) {
    .Call('emh_cRunsNumber', PACKAGE = 'emh', x)
}

cRunsLongest <- function(x) {
    .Call('emh_cRunsLongest', PACKAGE = 'emh', x)
}

cAsLevels <- function(logrets) {
    .Call('emh_cAsLevels', PACKAGE = 'emh', logrets)
}

cAsLogReturns <- function(levels, order) {
    .Call('emh_cAsLogReturns', PACKAGE = 'emh', levels, order)
}

cAsDifferences <- function(x, order) {
    .Call('emh_cAsDifferences', PACKAGE = 'emh', x, order)
}

cAsLogReturnsMatrix <- function(levels, order) {
    .Call('emh_cAsLogReturnsMatrix', PACKAGE = 'emh', levels, order)
}

cAsBinary <- function(rets) {
    .Call('emh_cAsBinary', PACKAGE = 'emh', rets)
}

cAsRollingResiduals <- function(rets, w) {
    .Call('emh_cAsRollingResiduals', PACKAGE = 'emh', rets, w)
}

cAsRollingTrend <- function(rets, w) {
    .Call('emh_cAsRollingTrend', PACKAGE = 'emh', rets, w)
}

cWindow <- function(data, window) {
    .Call('emh_cWindow', PACKAGE = 'emh', data, window)
}

cMatrixSubRows <- function(matrix, ix, size) {
    .Call('emh_cMatrixSubRows', PACKAGE = 'emh', matrix, ix, size)
}

cMatrixSubCols <- function(matrix, start, end) {
    .Call('emh_cMatrixSubCols', PACKAGE = 'emh', matrix, start, end)
}

cMomentum <- function(matrix) {
    .Call('emh_cMomentum', PACKAGE = 'emh', matrix)
}

cSort <- function(data) {
    .Call('emh_cSort', PACKAGE = 'emh', data)
}

cLarge <- function(data, k) {
    .Call('emh_cLarge', PACKAGE = 'emh', data, k)
}

cSmall <- function(data, k) {
    .Call('emh_cSmall', PACKAGE = 'emh', data, k)
}

